story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
    path('story1/', views.story1, name='story1'),
    path('home/', views.index, name='home'),
    path('course/', views.course, name='course'),
    path('addcourse/', views.addcourse, name='addcourse'),
    path('deletecourse/<str:pk>/', views.deletecourse, name='deletecourse')
]   

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.accordion, name='index'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.book, name='index'),
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name = 'logout'),
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls'))
]

story1/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model):
    nama_mata_kuliah = models.CharField(max_length=100)
    dosen_mata_kuliah = models.CharField(max_length=30)
    sks_mata_kuliah = models.CharField(max_length=3)
    deskripsi_mata_kuliah = models.CharField(max_length=200)
    semester_mata_kuliah = models.CharField(max_length=10)
    ruang_mata_kuliah = models.CharField(max_length=10)


class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=30)


class Orang(models.Model):
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)
    nama_orang = models.CharField(max_length=50)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your models here.
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

story1/forms.py
from django import forms
from .models import MataKuliah

class MatkulForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = [
            'nama_mata_kuliah',
            'dosen_mata_kuliah',
            'sks_mata_kuliah',
            'deskripsi_mata_kuliah',
            'semester_mata_kuliah',
            'ruang_mata_kuliah',
        ]

    matkul_attrs  = {
    'type' : 'text',
    'placeholder' : 'Nama Mata Kuliah'
    }

    dosen_attrs  = {
    'type' : 'text',
    'placeholder' : 'Nama Dosen'
    }

    sks_attrs  = {
    'type' : 'text',
    'placeholder' : 'Berapa SKS'
    }

    deskripsi_attrs  = {
    'type' : 'text',
    'placeholder' : 'Deskripsi'
    }

    semester_attrs  = {
    'type' : 'text',
    'placeholder' : 'Semester'
    }

    ruang_attrs  = {
    'type' : 'text',
    'placeholder' : 'Ruang Kuliah'
    }

    nama_mata_kuliah = forms.CharField(label='', required=True, max_length=100, widget=forms.TextInput(attrs=matkul_attrs))
    dosen_mata_kuliah = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=dosen_attrs))
    sks_mata_kuliah = forms.CharField(label='', required=True, max_length=3, widget=forms.TextInput(attrs=sks_attrs))
    deskripsi_mata_kuliah = forms.CharField(label='', required=True, max_length=200, widget=forms.TextInput(attrs=deskripsi_attrs))
    semester_mata_kuliah = forms.CharField(label='', required=True, max_length=10, widget=forms.TextInput(attrs=semester_attrs))
    ruang_mata_kuliah = forms.CharField(label='', required=True, max_length=10, widget=forms.TextInput(attrs=ruang_attrs))

story1/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .forms import MatkulForm
from .models import MataKuliah

response = {}

# Create your views here.
def index(request):
    return render(request, 'index.html')

def story1(request):
    return render(request, 'story1.html')

def course(request):
    matakuliah = MataKuliah.objects.all
    return render(request, 'form_course.html', {'matakuliah' : matakuliah})

def addcourse(request):
	form = MatkulForm(request.POST or None)
	if (form.is_valid and request.method == 'POST'):
		form.save()
		return redirect('/course')

	return render(request, 'form.html', {'form' : form})

def deletecourse(request,pk):
	matakuliah = MataKuliah.objects.get(id=pk)
	matakuliah.delete()
	return HttpResponseRedirect('/course')

		

story7/views.py
from django.shortcuts import render

# Create your views here.
def accordion(request):
    return render(request, 'story7.html')

story8/views.py
from django.shortcuts import render

# Create your views here.
def book(request):
    return render(request, 'story8.html')

story9/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import CreateUserForm

# Create your views here.
def homepage(request):
    return render(request, 'homepage.html')

def register(request):
    if request.user.is_authenticated:
        return redirect('story9:homepage')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('story9:login')

        context = {'form' :form}
        return render(request, 'register.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('story9:homepage')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('story9:homepage')
            else:
                messages.info(request, 'username or password is incorrect')

        context = {}
        return render(request, 'login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('story9:homepage')

story1/templates/base.html
<!doctype html>
<html lang="en">

{% load static %}
 
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/story7.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/story8.css' %}">


    <title>Story 3</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item, home-btn" href="/home">Home</a>
            <a class="nav-item, about-btn" href="#aboutme">About</a>
            <a class="nav-item, resume-btn" href="#resume">Resume</a>
            <a class="nav-item, project-btn" href="#project">Project</a>
            <a class="nav-item, contact-btn" href="#contact">Contact</a>
            <a class="nav-item, contact-btn" href="/story1">Story 1</a>
            <a class="nav-item, contact-btn" href="/addcourse">Add Course</a>
            <a class="nav-item, contact-btn" href="/course">Course</a>
          </div>
        </div>
      </nav>
       
     {% block content %}
     {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

story1/templates/form.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">

{% load static %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
  <input type="submit" value="Submit">
</form> 


{% endblock %}
      

story1/templates/form_course.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">

{% load static %}
{% block content %}
<h2>Daftar kelas-kelas:</h2>
<table>
    <tr>
        <th>Nama Kelas</th>
        <th>Nama Dosen</th>
        <th>Berapa SKS</th>
        <th>Deskripsi</th>
        <th>Semester</th>
        <th>Ruangan</th>
        <th>Delete</th>
    </tr>
    {% for i in matakuliah %}
    <tr>
    <td>{{ i.nama_mata_kuliah }}</td>
    <td>{{ i.dosen_mata_kuliah }}</td>
    <td>{{ i.sks_mata_kuliah}}</td>
    <td>{{ i.deskripsi_mata_kuliah }}</td>
    <td>{{ i.semester_mata_kuliah }}</td>
    <td>{{ i.ruang_mata_kuliah }}</td>
    <td><a href="{% url 'story1:deletecourse' i.id %}">Delete</a></td>
    {% csrf_token %}
    </tr>
    {% endfor %}
</table>


{% endblock %}

story1/templates/index.html
{% extends "base.html" %}
<!doctype html>
<html lang="en">

{% load static %}
 
  <head>
    <title>Story 3</title>
  </head>
  <body>
   {% block content %} 

    <div class="homepage" id="home">
        <div class="row justify-content-center">
            <div class="homepage-caption">
                <b>Hello, <br>
                I am <span class="name">Haidar Labib</span></b><br><br>
                Computer Science Student
            </div>
        </div>
    </div>

    <div class="aboutme-page" id="aboutme">
            <div class="image">
                <img src="{% static 'img/fotoprofile.jpg'%}" class= "img-fluid" alt="error">
            </div>
            <div class="aboutme-caption">
                <p><b>Hello!</b></p>
                    <p style= "font-size:70%">My name is Haidar Labib Bangsawijaya or labib in short.<br>
                    I’m currently a second year student at University of <br>
                    Indonesia studying computer science. I enjoy playing video<br>
                    games, sleeping, and reading manga.</p>
            </div>
        </div>

    <div class="resume-page" id="resume">
        <div class="row">
            <div class="col-1"></div>
            <div class="col">
                <h2 style="color: blue;"><b>Education</b></h2>
                <div class="media">
                    <img src="{% static 'img/unnamed.png'%}" class="mr-3" width="64" height="64" alt="vector">
                    <div class="media-body">
                        <h5 class="mt-0" style="color: blue;">2007 - 2013</h5>
                        <h3>SD-Islam Al-Azhar 9</h3>
                    </div>
                </div>
                <div class="media">
                    <img src="{% static 'img/unnamed.png'%}" class="mr-3" width="64" height="64" alt="vector">
                    <div class="media-body">
                        <h5 class="mt-0" style="color: blue;">2013 - 2016</h5>
                        <h3>SMP Islam Al-Azhar 8</h3>
                    </div>
                </div>
                <div class="media">
                    <img src="{% static 'img/unnamed.png'%}" class="mr-3" width="64" height="64" alt="vector">
                    <div class="media-body">
                        <h5 class="mt-0" style="color: blue;">2016 - 2019</h5>
                        <h3>SMA Islam Al-Azhar 4</h3>
                    </div>
                </div>
                <div class="media">
                    <img src="{% static 'img/unnamed.png'%}" class="mr-3" width="64" height="64" alt="vector">
                    <div class="media-body">
                        <h5 class="mt-0" style="color: blue;">2019 - present</h5>
                        <h3>University of Indonesia</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col"> </div>
            <div class="col">
                <h2 style="color: blue;"><b>Personal Experience</b></h2>
                <div class="media">
                    <img src="{% static 'img/briefcase.png'%}" class="mr-3" width="100" height="64" alt="vector">
                    <div class="media-body">
                        <h3>Coordinator Security at Social Project</h3>
                    </div>
                </div>
                <div class="media">
                    <img src="{% static 'img/briefcase.png'%}" class="mr-3" width="100" height="64" alt="vector">
                    <div class="media-body">
                        <h3>Media and Partner staff at COMPFEST</h3>
                </div>
            </div>
        </div>
    </div>
    </div>

    <div class="project-page" id="project">
        <div class="project-caption">
            Coming soon~
        </div>
    </div>

    <div class="contact-page" id="contact">
        <div class="row">
            <div class="col">
                <div class="media">
                    <img src="{% static 'img/instagram.png'%}" class="mr-2" width="120" height="64" alt="vector">
                    <div class="media-body">
                        <h5 class="mt-3">haidarlabib27</h5>
                </div>
            </div>
            <div class="media">
                <img src="{% static 'img/line.png'%}" class="mr-3" width="100" height="100" alt="vector">
                <div class="media-body">
                    <h5 class="mt-4">haidarlabib12</h5>
            </div>
        </div>
        <div class="media">
            <img src="{% static 'img/phone.png'%}" class="mr-3" width="100" height="43" alt="vector">
            <div class="media-body">
                <h5 class="mt-3">+628561348795</h5>
            </div>
        </div>
        <div class="media">
            <img src="{% static 'img/address.png'%}" class="mr-3" width="100" height="100" alt="vector">
            <div class="media-body">
                <h5 class="mt-4">Jl Pulo Sirih Barat 10, no. FE 506</h5>
            </div>
        </div>
            </div>
            <div class="col">
                <form>
                    <div class="form-group">
                        <input type="name" class="form-control" id="exampleInputName" placeholder="Name" >
                      </div>
                      <div class="form-group">
                        <input type="password" class="form-control" id="exampleInputPassword" placeholder="Email">
                      </div>
                      <div class="form-group">
                          <input type="message" class="form-control" id="exampleInputMessage" placeholder="Message">
                      </div>
                      <button type="send" class="btn btn-primary">Send</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}
    
  </body>
</html>

story1/templates/story1.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Haidar Labib</title>
</head>
{% block content %} 
<body>
    <div class="story1">
    <h1>Hello, Welcome to my very scuffed website!</h1>
    <img src="{% static 'img/foto1.jpg'%}" alt="my test" class ="box-img" width="250">
    <h2>About Me:</h2>
    <p>My name is Haidar Labib Bangsawijaya or u can call me labib in short.<br> 
        I'm currently a second year student at University of Indonesia studying computer science.<br>
        I enjoy playing video games, sleeping, and reading manga.
        
    </p>


    <h2>More Facts About Me:</h2>
    <ul>
        <li>NPM     : 1906400135</li>
        <li>Angkatan: Maung 2019</li> 
    </ul>

    <h2>Education History: </h2>
    <ul>
        <li>SMA Islam Al-Azhar 4</li>
        <li>SMP Islam Al-Azhar 8</li>
        <li>SD Islam Al-Azhar 9</li>
    </ul>

    <h2>You Can Check Me On: </h2>
    <a href="https://www.instagram.com/haidarlabib27/">
    <span><img src="{% static 'img/ig.png.png'%}" width="50"></span></a>
</div>
    {% endblock %}

</body>
</html> 

story7/templates/story7.html
{% extends "base.html" %}
{% load static %}

<!doctype html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/story7.css' %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


  </head>
  <body>
      {% block content %}
    <div class="container-accordion">
        <div class="acc">
        <button onclick="keatas()" class="arrow-up">^</button>
        <button onclick="kebawah()"class="arrow-down">v</button>
        <button class="accordion">Section 1</button>
            <div class="panel">
                <p>Section 1</p>
            </div>
        </div>

        <div class="acc">
        <button onclick="keatas()" class="arrow-up">^</button>
        <button onclick="kebawah()" class="arrow-down">v</button>
        <button class="accordion">Section 2</button>
            <div class="panel">
                <p>Section 2</p>
            </div>
        </div>

        <div class="acc">
        <button onclick="keatas()" class="arrow-up">^</button>
        <button onclick="kebawah()" class="arrow-down">v</button>
        <button class="accordion">Section 3</button>
            <div class="panel">
                <p>Section 3</p>
            </div>
        </div>
    </div> 

        
    <script src="{% static 'js/accordion.js' %}"></script>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script> -->

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
    {% endblock %}
  </body>
</html>

story8/templates/story8.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/story7.css' %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

  </head>
  <body>
    <h1>Books Finder</h1>
    <input id="search" placeholder="Title or Author">
    <button id="button" type="button">Search</button>
    <div id="result"></div>

    <script src="{% static 'js/books.js' %}"></script>
    <script src="{% static 'js/jquery-3.5.0.min.js' %}"></script>
  </body>

</html>

story9/templates/homepage.html
<!DOCTYPE html>
<html>
{% load static %}

{% if user and user.is_authenticated %}
<span id="hello-msg">Hello, {{request.user}}</span>
<span><a id="Button" href="{% url 'story9:logout' %}">logout</a></span>
{% else %}
<p>Please login first</p>
<span><a id="Button" href="{% url 'story9:login' %}">login</a></span>
{% endif %}
</html>

story9/templates/login.html
<!DOCTYPE html>
<html>
	{% load static %}
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;

		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				
				{% for message in messages %}
					<p>{{message}}</p>
				{% endfor %}
				
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'story9:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>